#!/bin/bash
echo " Iam learning devops with AWS"
PERSON1=$1 # THIS IS THE FIRST VALUE FROM COMMAND LINE"
PERSON2=$2 # THIS IS THE SECOND VALUE FROM COMMAND LINE"
echo " $PERSON1: HI $PERSON2 GOOD MORNING"
echo " $PERSON2: GOOD MORNING $PERSON1"
echo " $PERSON1: HOW R U $PERSON2"
echo " $PERSON2: i am good HOW R U $PERSON1"
